version: "3"

services:
  tasker:
    build: ./tasker
    image: tasker:alpha01
    container_name: tasker
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./tasker/:/tasker/"
    ports:
      - 8000:8000
    env_file:
      - env.container

  redis:
    image: redis:latest
    container_name: redis

  celery:
    build: ./tasker
    volumes:
      - "./tasker/:/tasker/"
    container_name: celery
    restart: on-failure
    command: celery -A task worker --loglevel=INFO -B
    depends_on:
      - tasker
    env_file:
      - env.container
