# Generated by Django 4.1.7 on 2023-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncresults',
            name='n_rows',
            field=models.IntegerField(null=True),
        ),
    ]
