# Generated by Django 4.1.7 on 2023-03-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_asyncresults_n_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncresults',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
